name: watson_assistant
description: Unofficial implementation of IBM Watson Assistant API for Flutter.
version: 0.0.1
author: Davide Bolzoni <davide.bolzoni59@gmail.com>
homepage: https://github.com/dbbd59/flutter-ibm-watson-assistant

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
